### ISSUE TITLE
Support newest Xcode & Swift

### ISSUE THREAD

**Issue by tomassliz** [krzysztofzablocki/KZFileWatchers#13]
Hi,
I would like to update the project to **Xcode 9.3** and **Swift 4.1**. I would love to make PR but firstly I want to hear if this change is wanted or not. I noticed that used pods versions are very old and that some small code improvements can be done.

**Comment by krzysztofzablocki** [comment]
would be great, I can give you contributor access as well if you'd like to join the team?

I've so many projects that I can only update many of them when I actually need it so any help is always appreciated 🙇

**Comment by tomassliz** [comment]
I understand 😉I would love to help and be a part of the team. It’s time to pay you back for your amazing work and everything what you do for iOS community 👍 still so little.
