### ISSUE TITLE
Objc Interoperability 

### ISSUE THREAD

**Issue by morzv** [krzysztofzablocki/KZFileWatchers#18]
Hi, I want to add interoperability with Objective-C by writing some wrappers above classes and enum, without modifying original sources.
It could be useful for project with legacy code base.

**Comment by krzysztofzablocki** [comment]
happy to accept PR that ads that ;)

**Comment by morzv** [comment]
I am ready to create PR, but I haven't access for pushing branch with code. Can you give me access, please?

**Comment by tomassliz** [comment]
@Jastic7 You don’t need access for this. You have to fork this repo, add some code into this fork and then make PR from it. More info how to create PR can be found here: https://help.github.com/articles/creating-a-pull-request/

**Comment by morzv** [comment]
Thank you, @tomassliz ! I forgot this way)

**Comment by morzv** [comment]
@krzysztofzablocki I am not sure, but it seems, that you should upload a new version of pod to the CocoaPods. Or, maybe I make some mistakes - the version of pod stayed 1.0.5 (instead of new 1.0.6, that merged) after I had ran `pod update` in my project.

**Comment by krzysztofzablocki** [comment]
sorry about that, pushed now @Jastic7
