### ISSUE TITLE
TextEdit is breaking the dispatch_source observation

### ISSUE THREAD

**Issue by uutkarshsingh** [krzysztofzablocki/KZFileWatchers#2]
Hi there,
Thanks for this project. I am trying this out at present but I am not sure how it works.In the sample source example ,when I run the app and open the text file the changes that are typed in the text file are reflected on the app only when the file is saved . This happens only the first time , rest of the time if I change the text and save again nothing gets changed.  This is contrary to what is happening in the GIF that has been attached to the project. Please tell tell how to make sure it works that way.

**Comment by krzysztofzablocki** [comment]
are you running it on simulator? what editor are you using to save the file?

**Comment by uutkarshsingh** [comment]
I am using simulator to run the project. I am using Textedit to make the changes to the file.Which editor is used in the GIF that has been put ?

**Comment by krzysztofzablocki** [comment]
TextEdit behaviour is triggering weird effect that only first change is firing callbacks, I'm not sure what exactly is wrong here, but if you use Sublime Text or Atom it should work fine

**Comment by krzysztofzablocki** [comment]
ok I fixed it in `0.1.2`, grab that version and it should work. It seems that VNODE_RENAME and VNODE_DELETE need to be treated same way and text edit generates the rename one

**Comment by uutkarshsingh** [comment]
Thanks a lot.Eager to try this out. Can I know good resource for learning Grand Central Dispatch ?
