### ISSUE TITLE
Bad implementation of time intervals

### ISSUE THREAD

**Issue by ArkadiGiniApps** [krzysztofzablocki/KZFileWatchers#27]
you have a bug in your computation of default time intervals.
`1/60` is an action on integers which results in a rounded number, specifically in a '0'

you should change the expression into: '1/60.0' if you want a floating point expression

**Comment by krzysztofzablocki** [comment]
You are incorrect, that's not how this works in Swift:
```swift
refreshInterval: TimeInterval = 1/60
```
isn't rounding to 0, because it knows they are doubles

**Comment by ArkadiGiniApps** [comment]
After retesting you are correct.
however its a strange behavior when the number literal are cast into TimeInterval before computation... guess its one more strange thing someone added to the compiler
