### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [krzysztofzablocki/KZFileWatchers#3]
Hi,
For iOS and macOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://bit.ly/2IWvGks)
- [Carthage Tutorial: Getting Started](https://bit.ly/2zes4dN)
- [Making Carthage-compatible Frameworks with Swift](https://bit.ly/2tXUofp)
- [Swift Cross Platform Framework](https://bit.ly/2ysgETA) (section [Configure targets for Carthage](https://bit.ly/2tZUOSt)) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by krzysztofzablocki** [comment]
if you or anyone else want to create PR with Carthage support, I'd be happy to merge it

**Comment by krzysztofzablocki** [comment]
This seems like it's already working given https://github.com/jarsen/DemoRPG/blob/master/Cartfile has it running
