### ISSUE TITLE
[Question] KZFileWatchers Fatal Error, Xcode 8.2.1, Swift 3.0.2

### ISSUE THREAD

**Issue by ghost** [krzysztofzablocki/KZFileWatchers#8]
Hi, from New Zealand! :-)

I like the idea of this framework and hopefully will be using it in an app I am developing, along with Freddy (for JSON data), and ReSwift (reactive states).

I downloaded this repo on 20 April 2017, and put only the source files into my project.

Recently, I have had a fatal runtime error on this piece of code in the Daemon class:
`try! fileWatcher.start(closure: { result in`

The full error is this:
`fatal error: 'try!' expression unexpectedly raised an error: trips.FileWatcher.Error.failedToStart("Failed to open file"): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.63/src/swift/stdlib/public/core/ErrorType.swift, line 178`

As seen in this screenshot of Xcode: http://imgur.com/a/cVQZT

I have adapted the Daemon code to initialize with an URL, then pass that as a path String to FileWatcher.Local as:
`    fileWatcher = FileWatcher.Local(path: String(describing: jsonURL))`

This is shown by the full URL (where 'Store' and 'state.trip' both exist):
`file:///Users/mikenorman/Library/Developer/CoreSimulator/Devices/72D4C7B2-B12E-4E0D-B520-A194237BCABA/data/Containers/Data/Application/FCA0A655-5F08-40C9-AAF4-0658C8346439/Library/Store/state.trip`

I am currently testing this to the iPhone 6s Simulator, which is working fine for any other builds.
The file I am trying to 'watch' is a JSON file (state.trip) in a 'Store' folder in the app's Library folder. 

Is this an invalid operation for the i386 architecture? I only want to use this on iOS.
`Thread 1: EXC_BAD_INSTRUCTION (code=EXC_i386_INVOP, subcode=0x0)`

I am not sure why it is throwing that fatal error, and any help will be awesome.

Thanks

--mike

**Comment by krzysztofzablocki** [comment]
Hey!

Any chance you could provide a sample project that reproduces the issue? seems odd and I've never seen this happen before

**Comment by ghost** [comment]
Hi Krzysztof.

I've sent you a personal e-mail with my project attached as a ZIP file.
I haven't fully tested if the JSON or ReSwift parts work, so don't be surprised if they don't.

Oh, I made an error in the title too. It's Swift 3.0.2, not 3.0.1.

Thanks.

--mike

**Comment by ghost** [comment]
Hi Krzysztof.

Good news. Found out what the fatal error is. My project now builds and runs again!

The error was caused by the `file://` component of a file URL in the path String, instead of just starting with `/Users/... ` at the beginning of the path. 

Solved it by taking a sub-string of my 'path' string, which trims off the leading `file://`.

I also tightened by Daemon class code to `init` a `path: String` again, and passing that directly to `fileWatcher = FileWatcher.Local(path: path)`. Cuts out some unnecessary code too.

Thanks for your help anyway. It was more a `user.error` than a code issue. ;-)

You can delete that project ZIP I sent you.

--mike

**Comment by krzysztofzablocki** [comment]
glad to hear it works now ;)
